name: learn-github-actions

run-name: ${{ github.actor }} is learning github learn-github-actions

on:
  push:
    branches:
      - 06-mar-2024
      - main

jobs:
  check-bats-version:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats 
      - run: bats -v
      